### ISSUE TITLE
Push new run_saved_model

### ISSUE THREAD

**Issue by quaeler** [cactuscommunications/syntaxnet-ops-hack#1]
Since i can't build a valid whl (because of the duplicate symbols i mentioned in the original ticket), i can't generate a model featuring the new output tensor. Could you check in the new model and let me know if that pip build target actually works for you? (and if it doesn't, how you're getting your changes into Python..)

Thanks

**Comment by marhlder** [comment]
You should now be able to build the pip package without linking issues. Again I am using my other repository: https://github.com/marhlder/parsey_mcparseface_export/tree/documents-from-tensor to export my model to a SavedModelBundle. 

Just to clarify: I had no need for the Python wheel :)

**Comment by quaeler** [comment]
Builds fine - thanks :- )
